spring:
  application:
    name: servicio-gateway
  config:
    import: optional:configserver:http://localhost:8888
#  profiles:
#    active: dev
# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
