spring:
  application:
    name: servicio-items
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
server:
  port: ${PORT:0}

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


