spring:
  application:
    name: servicio-items
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: microservicios de items
  svc:
    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}