spring:
  application:
    name: servicio-productos


server:
  port: ${PORT:0}


# Manejo del log en modo trazabilidad para observar el comportamiento de las variables
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.bykenyodarz.ventas.controllers

# Configuraciones de Eureka
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka